src = ["src", "tests"]
line-length = 144

[lint]
extend-select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # imports
    "I"
]

[lint.flake8-tidy-imports]
banned-module-level-imports = ["pyarrow", "polars", "ibis"]
