name: QA

on:
  workflow_call:

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: prek
      - run: uv sync --all-extras
      - uses: j178/prek-action@v2

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: pytest
      - run: uv sync --all-extras
      - run: uv run pytest
